config/routes.rb
Rails.application.routes.draw do



  resources :users, only: [:new, :create]

  resources :ideas do
    resources :reviews
  end

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end



  get 'welcome/index', as: :home

  get 'review/hide/:id', to: 'reviews#flag', as: 'review_flag'
  get 'idea/like/:id', to: 'ideas#like', as: 'like_idea'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new

      # alias_action :create, :read, :update, :destroy, to: :crud

      # if user.is_admin?
      #   can :manage, :all
      # end

      # can [:edit, :update, :destroy], Idea do |idea|
      can [:edit, :update, :destroy], Idea do |idea|
        idea.user == user
      end

      can :destroy, Review do |review|
        review.user == user
      end
      #
      can :create, Review do |review|
        user != review.idea.user
      end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord

  has_many :reviews
  belongs_to :user, optional: true

  validates(:title, {presence: true, uniqueness: true})
  validates(:body, {length: {minimum: 1, maximum: 1000}})


  before_validation :titleize_title


  def self.recent(number)
    order(created_at: :desc).limit(number)
  end

    private

    def titleize_title
      self.title = title.titleize if title.present?
    end

end

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :idea
  belongs_to :user, optional: true

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :first_name, presence: true
  validates :last_name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,
                                    uniqueness: {case_sensitive: false},
                                    format: VALID_EMAIL_REGEX

  before_validation :downcase_email

  has_many :ideas, dependent: :nullify

  def full_name
    "#{first_name} #{last_name}"
  end

  def downcase_email
    self.email&.downcase!
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def user_signed_in?

    if session[:user_id].present? && current_user.nil?
      session[:user_id] = nil
    end
      session[:user_id].present?
  end

  helper_method :user_signed_in?

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  helper_method :current_user

  def authenticate_user!
    if !user_signed_in?
      redirect_to new_session_path, notice: 'You must be logged in to access this feature'
    end
  end
  
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show, :edit]
  before_action :find_idea, only: [:show, :update, :edit, :destroy, :like]

  def index
    @ideas = Idea.all

  end


  def new
    @idea = Idea.new
  end


  def like
    @likes = @idea.likes += 1
    @idea.update(likes: @likes)
    redirect_to ideas_path
  end


  def create
    @idea = Idea.new(idea_params)
    @idea.user = current_user

    if @idea.save
      redirect_to idea_path(@idea), notice: 'Successfully created'
    else
      flash[:alert] = "oops, you fucked up! try again!"
      render :new
    end
  end

  def show
    @review = Review.new
    @idea.save
  end


  def edit
    head :unauthorized unless can? :edit, @idea
  end

  def update
    if !(can? :update, @idea)
      head :unauthorized
    elsif @idea.update(idea_params)
      redirect_to idea_path(@idea), notice: 'Successfully updated'
    else
      render :edit
    end
  end


  def destroy
    if can? :destroy, @idea
      @idea.destroy
      redirect_to @idea, notice: "Idea has been Removed"
    else
      flash[:alert] = 'Access Denied. Only the owner may delete this!'
      redirect_to @idea
    end
  end


  private


  def find_idea
    @idea = Idea.find(params[:id])
  end


  def idea_params
    idea_params = params.require(:idea).permit([:title, :body, :user_id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!

  def new
  end

  def index
  end

  def flag
    @review = Review.find params[:id]
    @review.update(is_flagged: !@review.is_flagged)
    @idea = @review.idea
    redirect_to idea_path(@idea)
  end

  def create
    @review = Review.new(review_params)
    @idea = Idea.find params[:idea_id]
    @review.idea = @idea
    @review.user = current_user

    if cannot? :create, @review
      flash[:alert] = "can't review your own product!!!"
      redirect_to @idea
    elsif
      @review.save
      redirect_to @idea, notice: 'Thank you for submitting a review!'
    else
      flash[:alert] = "Problem creating review"
      render 'products/show'
    end
  end

  def destroy
    @review = Review.find params[:id]
    @idea = Idea.find(params[:idea_id])

    if can? :destroy, @review
      @review.destroy
      flash[:notice] = "Review Successfully Removed"
      redirect_to @idea
    else
      flash[:alert] = 'Access Denied. Only the author may delete this review!'
      redirect_to @idea
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :body)
  end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    # we have the user's email/password from the params
    # 1. find the user by their email address
    # 2. if found, we authenticate the user with the given password
    # 3. if not found, we alert the user with wrong credentials

    user = User.find_by(email: params[:email])

    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to  home_path, notice: 'Thanks for signing in!'
    else
      flash.now[:alert] = 'no user by those credientials!'
      render :new

    end
  end


  def destroy
    session[:user_id] = nil
    redirect_to home_path, notice: "You've just logged out, see you next time!"
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    if @user.save
      session[:user_id] = @user.id
      redirect_to home_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :email,
      :password,
      :password_confirmation
    )
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def new_release
    respond_to do |format|
      format.html
      format.js
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/ideas/_form.html.erb
<%= form_for(idea) do |f| %>
  <div class="form-group">
    <%= f.label :title  %>
    <%= f.text_field :title, class: "form-control"  %>
  </div>
  <div class="form-group">
    <%= f.label :body  %>
    <%= f.text_area :body, class: 'form-control' %>
  </div>

</div class="form-group">
    <%= f.submit :submit, class: 'btn btn-primary'%>
</div>
<% end %>

app/views/ideas/edit.html.erb
<div class="container">
  <h1> edit page </h1>
<br>
  <h1><%= @idea.errors.full_messages.join(', ') %></h1>

<br>
<br>


  <%= render 'form', idea: @idea %>

app/views/ideas/index.html.erb
<h1>List of ideas: </h1>

<br>
<br>

<div class="pull-right">
  <div class="btn btn-primary btn-md" data-toggle="modal" data-target="#myModal" data-remote="url.html">New Idea</div>
  <%# link_to "New Idea", new_idea_path %>
</div>
<hr>

  <% @ideas.each do |idea| %>
    <strong><%= link_to "#{idea.title}", idea_path(idea) %></strong>
    <p> <%= idea.body %> </p>
    <p><strong>By: <%= idea.user.try(:full_name) %> </strong></p>
    <span> Likes: <%= idea.likes %><%= link_to 'like', like_idea_path(idea),  class: "btn btn-success btn-xs pull-right" %> </span>

    <hr>


    <% end %>


    <!-- Button trigger modal -->


    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="myModalLabel">Submit a New Idea</h4>
          </div>
          <div class="modal-body">
            <%= form_for :idea, url: ideas_path do |f| %>
              <div class="form-group">
                <%= f.label :title %><br>
                <%= f.text_field :title, class: "form-control" %>
              </div>

              <div class="form-group">
                <%= f.label :body %><br>
                <%= f.text_area :body, class: "form-control" %>
              </div>
          </div>
          <div class="modal-footer form-group">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= f.submit :submit, class: 'btn btn-primary' %>
          </div>
        </div><!-- /.modal-content -->
        <% end %>
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

app/views/ideas/new.html.erb
<%= form_for :idea, url: ideas_path do |f| %>
  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :body %><br>
    <%= f.text_area :body, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit %>
  </div>
<% end %>

app/views/ideas/show.html.erb
<h1> <%= @idea.title %> </h1>

<p><strong></strong><%= @idea.body %></p>
<strong>By: <%= @idea.user.try(:full_name) %></strong>
<hr>
<% if (can? :destroy, @idea) %>
  <%= link_to 'Delete', idea_path(@idea),
                                              method: :delete,
                                              data: { confirm: 'Are you sure?'} %>
<% end %>


<% if can? :edit, @idea %>
  <%= link_to 'Edit', edit_idea_path(@idea) %>
<% end %>


<h3> User Review(s) </h3>
<% @idea.reviews.each do |review| %>
  <hr>
  <% if review.is_flagged && !user_signed_in? %>
    <p><span class="glyphicon glyphicon-flag pull-left" style="color: red; font-size: 25px;"></span>
      <strong> * This review has been flagged for removal * </strong></p>
  <% elsif !review.is_flagged && !user_signed_in? %>
    <p><strong><%= review.user.try(:full_name) %> says: </strong>
    <p><%= review.body %></p>
  <% elsif review.is_flagged && @idea.user == current_user %>
    <p><span class="glyphicon glyphicon-flag pull-left" style="color: red; font-size: 25px;"></span>
      <strong> * This review has been flagged for removal * </strong>
    <span class="pull-right"><%= link_to 'Unflag', review_flag_path(review), class: 'btn btn-success btn-xs' %></span></p>
  <% else%>
    <p><strong><%= review.user.try(:full_name) %> says: </strong>
      <span class="pull-right"><%= link_to 'Flag', review_flag_path(review), class: 'btn btn-danger btn-xs' %></span></p>
      <p><%= review.body %></p>
  <% end %>


  <% if can? :destroy, review %>
    <%= link_to 'Delete', [@idea, review],
      method: :delete,
      data: {confirm: 'Are you sure?!!'}%>
  <% end %>
<% end %>


<% if user_signed_in? %>
  <hr>
  <h3> add a Review </h3>
  <%= form_for ([@idea, @review]) do |f| %>
    <div class="form-group">
      Review:<%= f.text_area :body, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.submit :submit, class: 'btn btn-primary'%>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IdeaFactory</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="container">
      <%= link_to 'Idea Factory', home_path, class: 'btn' %>
      |
      <%= link_to 'All Ideas', ideas_path, class: 'btn' %>
      |
      <%# link_to 'Submit New Idea', new_idea_path %>
      <a class="btn" data-toggle="modal" data-target="#myModal" data-remote="url.html">New Idea</a>
      |
      <% if user_signed_in? %>
        <span style='color: orange;' class="pull-right"> - Currently logged in as: <%= current_user.full_name %> - <%= link_to 'Log out', sessions_path, method: :delete %></span>
      <% else %>

        <%= link_to 'Log In', new_session_path, class: 'btn' %>
        |
        <%= link_to 'Sign Up', new_user_path, class: 'btn' %>
      <% end %>

      <% if flash[:notice] %>
        <div class='alert alert-success'><%= flash[:notice] %></div>
      <% elsif flash[:alert] %>
        <div class='alert alert-danger'><%= flash[:alert] %></div>
      <% end %>

      <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
              <h4 class="modal-title" id="myModalLabel">Submit a New Idea</h4>
            </div>
            <div class="modal-body">
              <%= form_for :idea, url: ideas_path do |f| %>
                <div class="form-group">
                  <%= f.label :title %><br>
                  <%= f.text_field :title, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :body %><br>
                  <%= f.text_area :body, class: "form-control" %>
                </div>
            </div>
            <div class="modal-footer form-group">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <%= f.submit :submit, class: 'btn btn-primary' %>
            </div>
          </div><!-- /.modal-content -->
          <% end %>
        </div><!-- /.modal-dialog -->
      </div><!-- /.modal -->



      <%= yield %>
    </div>
  </body>
</html>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<div class="container">

  <h1>Sign Up now !!!</h1>

  <h3 style='color: red;'><%= @user.errors.full_messages.join(', ') %></h3>

<div class="form-group">
  <%= form_for @user do |f| %>
  <div>
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: "form-control" %>
  </div>

  <div>
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: "form-control" %>
  </div>

  <div>
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control" %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
  </div>

  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>

  <br>

  <%= f.submit class: 'btn btn-success' %>

</div>

<% end %>

</div>

app/views/welcome/index.html.erb
<h1> You've Found the Idea Factory </h1>


<!-- <%= link_to 'All Ideas', ideas_path %>
<%= link_to 'Submit New Idea', new_idea_path %> -->